### ISSUE TITLE
Good name?

### ISSUE THREAD

**Issue by phated** [gulp-sourcemaps/comment#1]
I'm not sure if `comment` is too generic of a name for this module.  I thought about `map-comment` but it's going to have more methods than just a mapping method (like `comment.remove()` and `comment.prefix()`)

@nmccready thoughts?

**Comment by phated** [comment]
I'm guessing this is fine.  The methods will be exported as more verbose names from gulp-sourcemaps.

**Comment by nmccready** [comment]
Yeah this seems fine. I can't think of anything clever. Even if it is clever this lib will be kinda small for such a clever name.

**Comment by phated** [comment]
Alright, I guess I will close this.  Might change it if anything better and more descriptive pops out to me.
