### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by phated** [gulp-sourcemaps/comment#2]
@jonschlinkert I know you and @doowb have some scaffolding tools.  I'm churning out these modules but it's time consuming to copy the files from another module and then replacing the references with the new module.  Maybe I can create something like what you guys have to speed this up?  There's a handful more modules I need to create.

**Comment by phated** [comment]
Looking through `generate` and `update`, I'm a bit confused, so I guess this is also a request for help in getting started.

**Comment by doowb** [comment]
@phated I'll point out my workflow and @jonschlinkert can add more. We use `generate`, `update`, and `verb` for all of our projects.

**create a new project**

```sh
gen project git
```

For generate, there are a few other generators that we have, but to start with I use [generate-project](https://github.com/generate/generate-project) and [generate-git](https://github.com/generate/generate-git). `generate-project` has a bunch of "micro generators" included that create the individual files.


**update an existing project**

```sh
update
```

For `update`, I install it globally also `npm i -g update` and I have the following updaters configured to run by default:

![image](https://cloud.githubusercontent.com/assets/995160/24316759/1e586554-10c7-11e7-82ad-909abfb12a4a.png)

Each one in that list can be installed globally by prefixing `updater-` to the alias shown in that list. Then you can run `update --init` to choose the updaters you want to set as defaults.
I make sure I have everything committed in my project before running update.

**generate readme**

```sh
verb --init
verb
```

For `verb`, use the dev branch: `npm i -g verbose/verb#dev` and install `verb-generate-readme` to create the readme files. When running `verb` for the first time in a project it'll prompt to create a `.verb.md` file. This stubs out a template that's used. There's not much in that template, but by running `verb --init` and selecting the "default" layout, you'll get a lot more in the readme.

**install globally**

```sh
npm i -g update verbose/verb#dev generate generate-project generate-git
```

Those are the things that I can think of off the top of my head that I do with every project. There are more advanced features like creating your own generators and updaters and overriding templates by specifying them in your `~/templates` folder.

@jonschlinkert can talk more about those, plus I think this comment could be a start to a doc in [toolkit](https://github.com/node-toolkit/getting-started) docs.

**Comment by phated** [comment]
Thanks!  I was looking at the micro generator for .travis.yml and it seemed that it didn't fit my needs.  Can you explain the `~/templates` thing a bit more?  It was mentioned in the docs but nothing in the source code or tests guided me how that works.

**Comment by phated** [comment]
@doowb @jonschlinkert just tried generator and generate-project and it immediately threw because it isn't node 0.10-friendly 😭

**Comment by doowb** [comment]
The template overriding is handled in `generate`. When a generator loads a file from a "templates" folder, `generate` will check if the same file exists in `~/templates` and replace the contents.

**Comment by jonschlinkert** [comment]
> just tried generator and generate-project and it immediately threw because it isn't node 0.10-friendly

We're not happy about it.  Unfortunately, handlebars is in the dependency tree - which requires node 4.x or higher. 

We might be able to remove handlebars, but it probably won't be a trivial change (and I love handlebars). I need to think about that more (and get @doowb's opinion). 

Beyond that, there were only a few places where we used es6 templates etc. which we've since reverted. And that was published before we had this discussion on another issue.  We completely agree with you about compatibility, so we haven't published any es6 code since then. (I think you commented on one of the commits where we reverted es6 code).  There are a couple of libs left to convert, but those are used in the same tools that use handlebars, so we haven't rushed to remove the es6 stuff in those libs (but we will)

**Comment by jonschlinkert** [comment]
Oh, I was also going to comment on the micro-generator stuff, but it sounds like you weren't even able to run generate? (did I read that correctly? are you really on node 0.10.0 still locally?)

**Comment by phated** [comment]
> Unfortunately, handlebars is in the dependency tree - which requires node 4.x or higher.

Ah, that makes sense.

> We completely agree with you about compatibility, so we haven't published any es6 code since then. (I think you commented on one of the commits where we reverted es6 code).

👍 ❤️ 

> Oh, I was also going to comment on the micro-generator stuff, but it sounds like you weren't even able to run generate?

Nope, it crashed from ES6 stuff then crashed from dependency woes when I tried node 4

> (did I read that correctly? are you really on node 0.10.0 still locally?)

Yep, the only node that ever mattered.  Built my career and company on it and don't agree with anything iojs or 4+ (basically just iojs+) have done.

**Comment by phated** [comment]
Going to close this.
